# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180404_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog', to='post.Blog'),
        ),
    ]
